### ISSUE TITLE
quark is using qcacld-2.0 instead of prima

### ISSUE THREAD

**Issue by SkrilaxCZ** [MotorolaMobilityLLC/vendor-qcom-opensource-wlan-prima#1]
Is it possible to have a source drop for Moto MAXX XT1225 wlan driver, which instead of prima uses qcacld-2.0?

**Comment by sebirdman** [comment]
this is the same situation for clark

**Comment by rabih** [comment]
@tags07 Can we get an update on this?

**Comment by tags07** [comment]
Yes.. sorry was a mistake.. will post it soon.

**Comment by sebirdman** [comment]
@tags07 awesome! thank you for your quick response.

**Comment by vinimed** [comment]
Ticket is too old. If you are still interested, please re-open the issue.
