### ISSUE TITLE
Please release victara wlan l-mr1 source code.

### ISSUE THREAD

**Issue by parheliamm** [MotorolaMobilityLLC/vendor-qcom-opensource-wlan-prima#2]
Please release victara wlan l-mr1 source code.

**Comment by tags07** [comment]
What release tag are you looking for? I want to check to see if we already posted them but not mark the tags or if its in our pipeline.

thanks,
Gopi

**Comment by vinimed** [comment]
Ticket is too old. If you are still interested, please re-open the issue.
