### ISSUE TITLE
Code errors when building Marshmallow WiFi Driver

### ISSUE THREAD

**Issue by jame25** [MotorolaMobilityLLC/vendor-qcom-opensource-wlan-prima#4]
There are many code errors when building the latest Driver. Other versions have no such problem. Can someone please investigate this? Thanks.

**Comment by ShiroiKarasu6991** [comment]
The errors are mostly undeclared variables and implicit function declarations, which are serious enough to abort the build, regardless of the optimization level used (I generally use -O2 or -O3). One of the faulty files is either in the CORE/HDD/src folder or in CORE/MAC/src. I'll try to build a kernel with this driver here and provide more info.

**Comment by ShiroiKarasu6991** [comment]
And also, is this driver designed for all recent Moto series devices running Android 6.0 or just for one device? I've been trying to build it for titan/thea but no luck.

**Comment by charleseb** [comment]
Hi Icarus and jame25,

Could you please describe how are you building the kernel module?
What defconfig you are using and how are you building the wlan driver?
Could you also describe what tool chain you are using?

Thanks,
Charles

**Comment by ShiroiKarasu6991** [comment]
I'm building the driver as per standard in the stock kernel (as a separate loadable module). Here are the lines from my defconfig (falcon_defconfig):

```
#
# Qualcomm Atheros Prima WLAN module
#
# CONFIG_PRIMA_WLAN is not set
CONFIG_PRONTO_WLAN=m
# CONFIG_PRIMA_WLAN_BTAMP is not set
CONFIG_PRIMA_WLAN_LFR=y
CONFIG_PRIMA_WLAN_OKC=y
CONFIG_PRIMA_WLAN_11AC_HIGH_TP=y
CONFIG_WLAN_FEATURE_11W=y
CONFIG_QCOM_VOWIFI_11R=y
CONFIG_QCOM_TDLS=y
CONFIG_ENABLE_LINUX_REG=y
```

I'm using Linaro 5.2.

**Comment by vinimed** [comment]
Ticket is too old. If you are still interested on request, please re-open the issue.
